import type { Metadata } from "next";
import "./globals.css";
import Header from "./Header/header";
import ReactQueryProvider from "./ReactQueryProvider";
import Footer from "./Footer/footer";

export const metadata: Metadata = {
  title: "Beauty Land",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased" style={{ fontFamily: "Arial, Helvetica, sans-serif" }}>
        <ReactQueryProvider>
          <Header />
          {children}
          <Footer />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
